<?php

/**
 * Implements hook_theme().
 */
function nombres_theme($existing, $type, $theme, $path) {
  return [
    'listar_nombres' => [
      'variables' => [
        'data' => NULL,
        'form' => NULL,
      ],
      'template' => 'listar-nombres',
    ],
    'ver_nombres' => [
      'variables' => [
        'data' => NULL,
        'form' => NULL,
        'table' => NULL,
      ],
      'template' => 'ver-nombres',
    ],
    'animes' => [
      'variables' => [
        'data' => NULL,
        'form' => NULL,
        'table' => NULL,
      ],
      'template' => 'animes',
    ],
    'animes_admin' => [
      'variables' => [
        'data' => NULL,
        'form' => NULL,
        'table' => NULL,
      ],
      'template' => 'animes-admin',
    ],
    'animes_admin_ver' => [
      'variables' => [
        'data' => NULL,
        'form' => NULL,
        // 'table' => NULL,
      ],
      'template' => 'animes-admin-ver',
    ],
    'animes_ver' => [
      'variables' => [
        'data' => NULL,
        // 'form' => NULL,
        // 'table' => NULL,
      ],
      'template' => 'animes-ver',
    ],
  ];
}
